### ISSUE TITLE
稠密重建闪退

### ISSUE THREAD

**Issue by Dreamskya** [CaptainEven/SFM_PMVS_3DReconstruct_python#1]
![图片](https://user-images.githubusercontent.com/31117684/108588483-76c66680-7394-11eb-80d0-76c4021f0c58.png)

**Comment by Agui-Noodles** [comment]
I am getting the same error.
How did you solve it?
Any help would be appreciated.
Thanks

**Comment by yao1026** [comment]
I am getting the same error.
How did you solve it?
Any help would be appreciated.
Thanks

**Comment by yao1026** [comment]
> I am getting the same error. How did you solve it? Any help would be appreciated. Thanks
I'm having the same problem. Have you solved it?
